version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      python: 3.7
    commands:
      - pip3 install pipenv
      - pipenv install aws-sam-cli

  build:
    commands:
      - pipenv run sam package --s3-bucket $S3BUCKET --output-template-file $OUTPUT

artifacts:
  base-directory: .aws-sam
  files:
    - $OUTPUT