AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless API for a blog platform

Parameters:
  Environment:
    Type: String
    Default: Dev

  PostsTableName:
    Type: String
    Default: blog-posts

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs12.x
    Environment:
      Variables:
        posts_table: !Sub ${PostsTableName}

Resources:
  GetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}GetPosts
      CodeUri: handlers/get-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Sub ${PostsTableName}
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts
            Method: GET

  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}CreatePost
      CodeUri: handlers/create-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Sub ${PostsTableName}
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts
            Method: POST

  UpdatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}UpdatePost
      CodeUri: handlers/update-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${PostsTableName}
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts/{id}
            Method: PUT

  DeletePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}DeletePost
      CodeUri: handlers/delete-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub ${PostsTableName}
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts/{id}
            Method: DELETE

Outputs:
  RestApiUrl:
    Value: !Sub ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/

