AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless API for a blog platform

Parameters:
  Environment:
    Type: String
    Default: Dev

  PostsTableName:
    Type: String
    Default: blog-posts

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs10.x
    Environment:
      Variables:
        posts_table: !Ref PostsTableName

  Api:
    Cors:
      AllowHeaders: "'Authorization,Content-Type,Accept'"
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"

Resources:
  PostsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref PostsTableName
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}GetPosts
      CodeUri: handlers/get-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PostsTableName
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts
            Method: GET
        RestApiPathParams:
          Type: Api
          Properties:
            Path: /posts/{id}
            Method: GET

  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}CreatePost
      CodeUri: handlers/create-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref PostsTableName
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts
            Method: POST

  UpdatePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}UpdatePost
      CodeUri: handlers/update-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTableName
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts/{id}
            Method: PUT

  DeletePost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}DeletePost
      CodeUri: handlers/delete-post
      Handler: handler.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTableName
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /posts/{id}
            Method: DELETE

  GetPresignedUrl:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}GetPresignedUrl
      CodeUri: handlers/get-presigned-url
      Handler: handler.lambdaHandler
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: '*'
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /url
            Method: POST
        

Outputs:
  RestApiUrl:
    Value: !Sub ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/

